### ISSUE TITLE
Replace lib/Broker with nsIObserver

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search-addon#102]
nsIObserver seems to be the standard solution in Gecko for observing objects.

Use it instead of our half-baked broker code.

https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions/XUL_School/Observer_Notifications

**Comment by jaredhirsch** [comment]
Maybe ES7 object.observe?

**Comment by 6a68** [comment]
https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions/XUL_School/Observer_Notifications

`nsIObserver` seems to be the standard solution in Gecko for observing objects.

**Comment by jaredhirsch** [comment]
After learning a little more about the Gecko way, I think nsIOBserver is intended for situations in which a service is reused across many windows. That's not really the case with our extension code.

I'm going to close this for now. We can do another "airing of grievances" refactoring bug generation pass post-Orlando.
