### ISSUE TITLE
Addon broken in nightly

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search-addon#123]
Theory: need to modify our XBL inheritance scheme to extend and replace the new popup, rather than the old popup.

**Comment by nchapman** [comment]
What other prerelease channels have this issue?

**Comment by jaredhirsch** [comment]
Happily, this appears to be a trivial error.

The cause seems to be a startup race: if Transport.init() is called before the Broker is registered, then I see `TypeError: window.US.broker is undefined` in the browser toolbox console. Slowing the startup process (by stepping through in a debugger) prevents the error from being displayed.

I expect this bug will be fixed by properly using a sandbox or some other method that lets us resolve a deferred when all of the files are fully loaded, and only then continue the startup process.
