### ISSUE TITLE
cancel search suggestions if searchTerm has changed

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search-addon#15]
also maybe set an isSearching state, and cancel anything in-flight if something new is fired.

**Comment by jaredhirsch** [comment]
@nchapman what are good STR for this, just watch the packets flowing to the iframe?

I'm wondering if this will be fixed by fixing the synchronization race in #16.

**Comment by nchapman** [comment]
> @nchapman what are good STR for this

I don't know... I think we just identified that we could have outstanding requests for data that may not be meaningful after each keystroke. We could debounce keypresses as a way to fix this as well...

**Comment by jaredhirsch** [comment]
From what I can tell, the search suggestion controller automatically kills any in-flight requests when a new request is created.

I can't repro this right now; closing, will reopen if it reappears.
