### ISSUE TITLE
make the height of the iframe match the height of the content

### ISSUE THREAD

**Issue by johngruen** [mozilla/universal-search-addon#19]
Currently the iframe height is fixed, it should respond to changes in the height of the underlying content.

**Comment by jaredhirsch** [comment]
If we're keeping most of the display logic on the iframe side, this seems like it would open up a rendering performance can o' worms.

We could implement adjustable height something like this:
- initially, the browser tells the iframe its width and height
- as results are rendered, the iframe requests a height change.
  - the browser resizes the iframe's container, then calls back with the updated width and height.

The user experience might be not awesome, though. 

Imagine this: you type a few chars in the urlbar. Then what happens?
- popup opens and displays an empty iframe
- stuff is sent to iframe
- iframe renders stuff
- iframe waits a turn, then checks its DOM to see the rendered height
- iframe asks browser to adjust height
- browser adjusts height (I think this would trigger a reflow)
- browser tells iframe the height has changed

This whole sequence of events might happen 5 times in one second, if you're typing a familiar word. Re-adjusting the height and touching the DOM to check height many times a second just seems like a recipe for jank.

We could try to throttle the number of resizes per second, but it might lead to laggy-feeling UI as you notice a flash of content overflowing the edge of the frame, then the frame jumping to fit it.

We can try implementing this, but I'm skeptical. OTOH a big empty white box isn't ideal, either.

@nchapman what say ye?

**Comment by nchapman** [comment]
Yeah I agree this could be janky, but unless we decide to have a fixed number of results at all times (might be possible once we have smart enough tech but that's going to be a while), I think this is unavoidable. Let's try it and see how bad it is. I bet we can make the throttling smarter to eek out extra performance (calculate height by number of items instead of checking the dom, only incrementally resize if the height grows by a certain amount, etc).

**Comment by johngruen** [comment]
Ditto @nchapman , we could define some environmental vars that let us return the height based on the number of results so there's not a lot of DOM-dependent calculation.

**Comment by jaredhirsch** [comment]
Yeah, good point. The Ampersand code should be able to tell you how many items have been rendered without touching the DOM.

Let's figure out a simple API and implement this next week?

**Comment by jaredhirsch** [comment]
First guess at an API after letting this sit for a long time:
1. popup sends height in the popupOpen signal
2. iframe sends update-height signal with new height request
3. popup adjusts height, pings back with the new height (just to confirm)
