### ISSUE TITLE
Figure out how to uninstall cleanly

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search-addon#4]

**Comment by nchapman** [comment]
We should try to add the search box back to the toolbar on uninstall.

**Comment by jaredhirsch** [comment]
> We should try to add the search box back to the toolbar on uninstall.

Yup. I think we can do even better: if you had the search box visible on install, put it in the same spot in the toolbar on uninstall.

**Comment by jaredhirsch** [comment]
closing in favor of #17
