### ISSUE TITLE
let vs const vs var

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search-addon#42]
I casually noticed a few places in the code where we specify `const` and `let` instead of plain ol' `var`.

Now that we're using ESLint (yay!), we can get a bit fancy and straight out forbid the use of `var` in the codebase and enforce either `let` or `const` globally.
- [`no-var`](http://eslint.org/docs/rules/no-var) - require `let` or `const` instead of `var` (off by default).
- [`prefer-const`](http://eslint.org/docs/rules/prefer-const) - suggest using of `const` declaration for variables that are never modified after declared (off by default).

**Comment by jaredhirsch** [comment]
You know, I really don't have a problem with a dynamically-scoped `this` in a lexically-scoped world, but `var` certainly isn't _so amazing_ that we should hang onto it at this point.

I say let's do it.
