### ISSUE TITLE
Add CHANGELOG?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search-addon#65]
It may be nice to have a handy CHANGELOG to this repo so we can see what changes betweenst releases, etc.

Possibly use something like:
- https://www.npmjs.com/package/gulp-changelog-release
- https://www.npmjs.com/package/gulp-conventional-changelog

(ref: https://github.com/mozilla/universal-search-content/issues/41)

**Comment by jaredhirsch** [comment]
Something like a high-level, handwritten "here's what is new" description might be better.

If we move to A/B testing, we'll have to carefully advertise features to users, as they may or may not see them.

**Comment by jaredhirsch** [comment]
The commit history is descriptive enough for me, closing.
