### ISSUE TITLE
un-revert the rdf templating revert

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search-addon#67]

**Comment by pdehaan** [comment]
@6a68 Is something like this "good enough(tm)"?

#### /package.json

``` js
"scripts": {
  "postinstall": "npm run build"
}
```

That way, after you run `npm install`, it will do a `gulp build` which will generate the `src/*.rdf` files from the templates (then copy them into `dist/`).

**Comment by jaredhirsch** [comment]
@pdehaan Is there some reason we don't want to leave the generated rdf files in the repo? You could insert a comment that says, "this file is generated from whatever.template, don't modify this directly".

**Comment by jaredhirsch** [comment]
I mention this option because `npm install` is a weird thing to require for an addon, and the initial setup is pretty tricky already.

**Comment by pdehaan** [comment]
![](https://31.media.tumblr.com/58854669340fd9b8385071975311d37f/tumblr_inline_nrbphsPiKj1s0m7nr_500.gif)

@6a68: Yeah, that'll work too. I'll PR that tomorrow.

**Comment by pdehaan** [comment]
Ref: #60
