### ISSUE TITLE
add navigational query service to results

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search-addon#7]
https://github.com/mozilla/universal-search-suggest

**Comment by jaredhirsch** [comment]
We've adopted a principle of minimizing the amount of code not in the iframe, because that code has to get reimplemented when we eventually build a web server for all this.

So, we'll keep the suggestion service on the iframe side. Closing this bug accordingly.

**Comment by thovden** [comment]
So we need to deploy the latest version to the  suggestion service. It is not so currently
